# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "master", "Deployment", "API" ]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  nunittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd api && dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          pgconn: ${{secrets.PGCONN}}
          JWT: ${{secrets.JWT}}

      - name: Run tests once API is running (sleep interval set to 60 seconds)
        run: cd integration_tests && sleep 60 && dotnet build && dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}
          JWT: ${{secrets.JWT}}

      - name: Shutdown Web API once the tests are done running
        run: kill $API_PID
